spring.application.name=water_station

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# DB properties
spring.datasource.url=jdbc:mysql://localhost:3313/water_station
spring.datasource.username=mark
spring.datasource.password=madmin

# flyway settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# spring.security.user.name=admin
# spring.security.user.password=admin